### ISSUE TITLE
About neighborhood defination

### ISSUE THREAD

**Issue by rlacjfjin** [nduc4nh/Variable-Neighborhood-Search#1]
Hi,
In your defination of neighborhoods, is it only valid for tsp types(tsp,vrp)? 
Or how efficient the neighborhood in specific problem(such as tsp, scheduling)?

Thanks,

**Comment by nduc4nh** [comment]
Hi ,

Thank you for your question, as far as I know, the definition of the neighborhoods depends on how we encode our solution. In tsp, the solution is commonly encoded in the form of permutation. That is why I choose Neighborhood operation such as two-opt, swap-move.. There could be many problems using permutation encoding not only tsp so I think such Neighborhoods are not only for TSP
